### ISSUE TITLE
Simulation starts and immeatetly quits

### ISSUE THREAD

**Issue by TheIceCreamBear** [ucfcs/VizCon#64]
When compiling a file, and running it by going to the visualizer and starting the simulation, the simulation starts but immediately prints a python-related error.

```Traceback (most recent call last):
  File "E:\Programming\js\VizCon\concurrency\controller\script.py", line 15, in start
    _start(base64.b64decode(exe).decode(), terminalOutputFile, visualizerMode)
  File "E:\Programming\js\VizCon\concurrency\controller\script.py", line 199, in _start
    thread_man = ThreadManager(main_thread)
UnboundLocalError: local variable 'main_thread' referenced before assignment```

This seems to be new since the merging of the mingw branch.

**Comment by TheIceCreamBear** [comment]
As a note, this error also occurred on macOS. Linux was not tested.

**Comment by RyanG10** [comment]
The simplest fix it to move the call to [vizconSemCheck(); (Line 138)](https://github.com/ucfcs/VizCon/blob/f07043fc0fcb82e3d21be558812d6fb90e0a842e/concurrency/lldb_lib.c#L138) to before the call to [vc_internal_init(); (Line 137)](https://github.com/ucfcs/VizCon/blob/f07043fc0fcb82e3d21be558812d6fb90e0a842e/concurrency/lldb_lib.c#L137).

The reason it doesn't work currently is a bit of a mess. `vc_internal_init` sets the global `isLldbActive` variable, which means all semaphores will use the LLDB stuff. As it's written currently, `vizconSemCheck` tries to wait on a platform semaphore that doesn't exist (poor error handling in the Python script hides the error, but it's just an exception from calling a function like WaitForSingleObject with a NULL semaphore). The `vizconSem` isn't even used when LLDB is active, so in principle it would be nice to avoid initializing it at all in that case. But just removing the call doesn't work because LLDB does actually use the platform semaphore code for some stuff, and that code expects `vizconSem` to be initialized. As I said, it's a bit of a mess. So we could just move the one line for a quick fix, but the code is also begging for a minor refactor/cleanup.

```diff
int main()
{
+   vizconSemCheck();
    vc_internal_init();
-   vizconSemCheck();
    int ret = userMain();
    vizconSemCheck();
    return ret;
}
```

**Comment by TheIceCreamBear** [comment]
Sounds good. @RyanG10 can you create an issue documenting what needs to be refactored/cleaned up so we have it documented, and I will get a PR to do this quick fix for this issue.
